name: 'google_play_source_integration_tests'
version: '0.2.0'
profile: 'integration_tests'
config-version: 2

vars:
  google_play_schema: google_play_source_integration_tests
  google_play_source:
    stats_installs_app_version_identifier: "stats_installs_app_version"
    stats_crashes_app_version_identifier: "stats_crashes_app_version"
    stats_ratings_app_version_identifier: "stats_ratings_app_version"
    stats_installs_device_identifier: "stats_installs_device"
    stats_ratings_device_identifier: "stats_ratings_device"
    stats_installs_os_version_identifier: "stats_installs_os_version"
    stats_ratings_os_version_identifier: "stats_ratings_os_version"
    stats_crashes_os_version_identifier: "stats_crashes_os_version"
    stats_installs_country_identifier: "stats_installs_country"
    stats_ratings_country_identifier: "stats_ratings_country"
    stats_store_performance_country_identifier: "stats_store_performance_country"
    stats_store_performance_traffic_source_identifier: "stats_store_performance_traffic_source"
    stats_installs_overview_identifier: "stats_installs_overview"
    stats_crashes_overview_identifier: "stats_crashes_overview"
    stats_ratings_overview_identifier: "stats_ratings_overview"
    earnings_identifier: "earnings"
    financial_stats_subscriptions_country_identifier: "financial_stats_subscriptions_country"

dispatch:
  - macro_namespace: dbt_utils
    search_order: ['spark_utils', 'dbt_utils']

seeds:
  google_play_source_integration_tests:
    stats_installs_overview:
      +column_types:
        active_device_installs: "{{ 'int64' if target.type == 'bigquery' else 'bigint' }}"
    stats_ratings_app_version:
      +column_types:
        app_version_code: "{{ 'int64' if target.type == 'bigquery' else 'bigint' }}"
